/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.WinRegistry;
import java.awt.event.KeyEvent;
import java.lang.reflect.InvocationTargetException;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario-pc
 */
public class JframeInicioLoginBD extends javax.swing.JFrame {

    static boolean bandera = false;
    static JframeLoginClient login = new JframeLoginClient();

    /**
     * Creates new form LoginBD
     *
     * @param parametro
     */
    public JframeInicioLoginBD(boolean parametro) {
        if (parametro) {
            bandera = parametro;
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblip = new javax.swing.JLabel();
        TextoIP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        TextoUsuario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblClave = new javax.swing.JLabel();
        TextoClave = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario de inicio de sesión de base de datos");
        setBackground(new java.awt.Color(255, 102, 0));
        setName("FrameLoginBD"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/conection.png"))); // NOI18N
        lblImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblImagen)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblImagen)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel5);

        lblip.setText("IP O NOMBRE DEL SV");
        jPanel1.add(lblip);
        jPanel1.add(TextoIP);

        jPanel4.setPreferredSize(new java.awt.Dimension(361, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        lblUsuario.setText("USUARIO DE BD");
        lblUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblUsuario);
        jPanel1.add(TextoUsuario);

        jPanel3.setPreferredSize(new java.awt.Dimension(361, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        lblClave.setText("CONTRASEÑA DEL USUARIO DE BD");
        jPanel1.add(lblClave);
        jPanel1.add(TextoClave);

        btnConectar.setText("CONECTAR");
        btnConectar.setPreferredSize(new java.awt.Dimension(100, 53));
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });
        btnConectar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConectarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        this.conectar();

    }//GEN-LAST:event_btnConectarActionPerformed

    private void conectar() {
        try {
            if ( !TextoIP.getText().equals("") && !TextoUsuario.getText().equals("") && !TextoClave.getText().equals("")) {
                WinRegistry.createKey(WinRegistry.HKEY_CURRENT_USER, "SOFTWARE\\JAVAPROYECTO");
                //Aqui insertamos el usuario de la base de datos
                WinRegistry.writeStringValue(WinRegistry.HKEY_CURRENT_USER, "SOFTWARE\\JAVAPROYECTO", "Ip", TextoIP.getText());

                //Aqui insertamos el usuario de la base de datos
                WinRegistry.writeStringValue(WinRegistry.HKEY_CURRENT_USER, "SOFTWARE\\JAVAPROYECTO", "User", TextoUsuario.getText());

                //Aqui la contraseña la contraseña
                WinRegistry.writeStringValue(WinRegistry.HKEY_CURRENT_USER, "SOFTWARE\\JAVAPROYECTO", "Clave", TextoClave.getText());

                //Checking if prefs exists
                boolean existe = false;
                for (String readStringSubKey : WinRegistry.readStringSubKeys(WinRegistry.HKEY_LOCAL_MACHINE, "SOFTWARE\\JAVASOFT")) {
                    if (readStringSubKey.equals("Prefs")) {
                        existe = true;
                    }
                }
                if (existe == false) {
                    System.out.println("****TODO MENSAJE DE WARNING QUE SALGA NO ES NINGUN PROBLEMA ES UN BUG CON LA LIBRERIA QUE ESCRIBE EN EL REGISTRO*** \n Esta Advertencia se soluciona creando la clave en HKEY_LOCAL_MACHINE\\Software\\JavaSoft\\[Prefs] en el registro \n Para entrar al registro presione la tecla de Inicio + R, escribe regedit y busca la ruta anteriormente mencionada para crear la clave Prefs");

                }
                //Finish checking

                login.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "No puedes dejar los campos en blanco.");
            }
        } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
            JOptionPane.showMessageDialog(null, e.getStackTrace());
        }
    }


    private void btnConectarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConectarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.conectar();
        }
    }//GEN-LAST:event_btnConectarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeInicioLoginBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeInicioLoginBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeInicioLoginBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeInicioLoginBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    boolean existeDos = false;
                    String registro = WinRegistry.readString(WinRegistry.HKEY_CURRENT_USER, "SOFTWARE\\JAVAPROYECTO", "Ip");
                    if (registro == null && bandera == false) {
                        //Checking if prefs exists
                        for (String readStringSubKey : WinRegistry.readStringSubKeys(WinRegistry.HKEY_LOCAL_MACHINE, "SOFTWARE\\JAVASOFT")) {
                            if (readStringSubKey.equals("Prefs")) {
                                existeDos = true;
                            }
                        }
                        if (existeDos == false) {
                            System.out.println("****TODO MENSAJE DE WARNING QUE SALGA NO ES NINGUN PROBLEMA ES UN BUG CON LA LIBRERIA QUE ESCRIBE EN EL REGISTRO*** \n Esta Advertencia se soluciona creando la clave en HKEY_LOCAL_MACHINE\\Software\\JavaSoft\\[Prefs] en el registro \n Para entrar al registro presione la tecla de Inicio + R, escribe regedit y busca la ruta anteriormente mencionada para crear la clave Prefs");

                        }

                        JframeInicioLoginBD loginbd = new JframeInicioLoginBD(false);
                        loginbd.setVisible(true);
                    } else {
                        //Checking if prefs exists
                        boolean existenciaTres = false;
                        for (String readStringSubKey : WinRegistry.readStringSubKeys(WinRegistry.HKEY_LOCAL_MACHINE, "SOFTWARE\\JAVASOFT")) {
                            if (readStringSubKey.equals("Prefs")) {
                                existenciaTres = true;
                            }
                        }
                        if (existenciaTres == false) {
                            System.out.println("****TODO MENSAJE DE WARNING QUE SALGA NO ES NINGUN PROBLEMA ES UN BUG CON LA LIBRERIA QUE ESCRIBE EN EL REGISTRO*** \n Esta Advertencia se soluciona creando la clave en HKEY_LOCAL_MACHINE\\Software\\JavaSoft\\[Prefs] en el registro \n Para entrar al registro presione la tecla de Inicio + R, escribe regedit y busca la ruta anteriormente mencionada para crear la clave Prefs");

                        }
                        //Finish checking
                        JframeInicioLoginBD loginbd = new JframeInicioLoginBD(bandera);
                        loginbd.dispose();
                        login.setVisible(true);
                    }
                } catch (IllegalArgumentException | IllegalAccessException | InvocationTargetException e) {
                    JOptionPane.showMessageDialog(null, e.getStackTrace());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextoClave;
    private javax.swing.JTextField TextoIP;
    private javax.swing.JTextField TextoUsuario;
    private javax.swing.JButton btnConectar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblip;
    // End of variables declaration//GEN-END:variables
}
